Exhibition/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from .views import UploadView, HeartSoundsDemonstrate, HeartSoundsList

app_name='Exhibition'

urlpatterns = [
    path('upload/', login_required(UploadView.as_view()), name='upload'),
    path('file_detail/<int:id>/', login_required(HeartSoundsDemonstrate.as_view()), name='file_detail'),
    path('file_list/<int:page>/', HeartSoundsList.as_view(), name='file_list'),
    path('file_download/<int:id>', views.download, name='file_download')
]

HeartSoundsSimplified/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from tyadmin_api.views import AdminIndexView
from django.views.static import serve
import Index.urls
urlpatterns = [
    path('',include('Index.urls',namespace='Index')),
    path('user/',include('User.urls',namespace='User')),
    path('exhibition/',include('Exhibition.urls',namespace='Exhibition')),
    re_path('^xadmin/.*', AdminIndexView.as_view()),
    path('api/xadmin/v1/', include('tyadmin_api.urls')),
    re_path('media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]

User/urls.py
from django.urls import path
from . import views
from .views import RegisterView, ForgetPasswordView, SubmitEmailUsernameView,LogoutView,LoginView

app_name='User'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('passwordforget/', ForgetPasswordView.as_view(), name='forgetpassword'),
    path('pfcode/', SubmitEmailUsernameView.as_view(), name='emailusername'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh" class="h-100 translated-ltr">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column h-100">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/" >HeartSounds</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'User:login' %}">登录</a>
                </li>
                <li class="nav-item">
                    {% if user.username %}
                        <a href="{% url 'User:logout' %}" class="nav-link">登出</a>
                    {% endif %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        菜单
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>

            </ul>
            <span class="navbar-brand text-center">
                        {% if user.username %}
                        Hello,{{ user }}
                        {% endif %}
            </span>
            <form class="d-flex" action="/" method="post">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="暂时没有做该功能" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">搜索</button>
            </form>
        </div>
    </div>
</nav>
<main class="flex-shrink-0">

{% if repetloginerror %}
    {{ repetloginerror }}
{% endif %}

    {% block content %}{% endblock %}
</main>
<!-- 最下面版权区 -->
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <p class="text-center text-muted">© 2020 心音项目组</p>
    </div>
</footer>
</body>

templates/downFileError.html
{% extends "base.html" %}
{% block title %}
文件下载失败
{% endblock %}
{% block content%}
<div>
<p>{{ message }}</p>
</div>
{% endblock %}

templates/file_detail.html
{% extends "base.html" %}
{% block content %}
<div>
    <table class="table">
        <thred>
            <tr>
                <th scope="col">心音名</th>
                <th scope="col">描述</th>
                <th scope="col">创建时间</th>
            </tr>
        </thred>
        <tbody>
        <tr>
            <td>{{ heartsounds_list.name }}</td>
            <td>{{ heartsounds_list.description }}</td>
            <td>{{ heartsounds_list.created_time }}</td>
            <td><span><a href="{% url 'Exhibition:file_download' heartsounds_list.id %}" class="text-decoration-none" >下载</a></span></td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

templates/forget_password.html
{% extends "base.html" %}
{% block content%}
<form class="form-signin" action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit" class="btn btn-outline-success">
</form>
{% endblock %}

templates/heartsounds_list.html
{% extends "base.html" %}
{% block content %}
    <div class="container-fluid">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">心音文件名</th>
                <th scope="col">采样来源</th>
                <th scope="col">采样时间</th>
                <th scope="col">采样方式</th>
                <th scope="col">采样频率</th>
            </tr>
            </thead>
            <tbody>
            {% for heartsounds in heartsounds_introduce_list %}
                <tr>
                    <th scope="row">{{ heartsounds.id }}</th>
                    <td><a href="{% url 'Exhibition:file_detail' heartsounds.id %} " target="_blank" class="text-decoration-none">{{ heartsounds.name }}</a></td>
                    <td>{{ heartsounds.sample_from }}</td>
                    <td>{{ heartsounds.duration_for_sample }}</td>
                    <td>{{ heartsounds.style_of_sampling }}</td>
                    <td>{{ heartsounds.sample_frequency }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% if is_paginated %}
        <div class="pagination-lg text-center">
            <span class="page-link">
                {% if page_obj.has_previous %}
                    <a href="{% url 'Exhibition:file_list' page_obj.previous_page_number %}" class="btn btn-outline-success">上一页</a>
                {% endif %}
                <span>The {{ page_obj.number }} page</span>
                {% if page_obj.has_next %}
                    <a href="{% url 'Exhibition:file_list' page_obj.next_page_number %}" class="btn btn-outline-success">下一页</a>
                {% endif %}
                <a href="{% url 'Exhibition:file_list' 1 %}" class="btn btn-outline-success">第一页</a>
                <span class="page-current">
                    total {{ page_obj.paginator.num_pages }} page
                </span>
                <a href="{% url 'Exhibition:file_list' page_obj.paginator.num_pages %}" class="btn btn-outline-success">最后一页</a>
            </span>
        </div>
    {% endif %}


{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
心音主页
{% endblock %}

        <!-- 内容主界面 -->
{% block content %}
    
    {% block user %}
    {{ user.name }}
    {% endblock %}
    {% if repeatloginmessage %}
        <div>
            <p class="text-center"><strong>{{ repeatloginmessage }}</strong></p>
        </div>
    {% endif %}

    <div class="container p-5 my-8 border">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5" aria-label="Slide 6"></button>
            </div>

            <div class="carousel-inner col-sm-3 col-md-3 container-fluid">
                <div class="carousel-item">
                    <img src="{% static 'images/heartsounds_images/wallhaven-1km6lv.jpg' %}" class="img-thumbnail rounded mx- d-block" alt="...">
                </div>
                <div class="carousel-item active">
                    <img src="{% static 'images/heartsounds_images/wallhaven-3z8er9.jpg' %}" class="img-thumbnail rounded mx-auto d-block" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/heartsounds_images/wallhaven-3z8526.jpg' %}" class="img-thumbnail rounded mx-auto d-block" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/heartsounds_images/wallhaven-9mwoj1.jpg' %}" class="img-thumbnail rounded mx-auto d-block" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/heartsounds_images/wallhaven-8o1mkj.jpg' %}" class="img-thumbnail rounded mx-auto d-block" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>


    <br><br><br>
    <div class="text-center">
    <span>
        <a href="{% url 'Exhibition:upload' %}"  class="btn btn-outline-success">上传文件</a>
        <a href="{% url 'Exhibition:file_list' page=1 %}" class="btn btn-outline-success">文件列表</a>
    </span>
    </div>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}
心音登录
{% endblock %}
<!-- 内容主界面 -->
{% block content %}
<br>
<br>

    <div class="container text-center">
        <div class="form-row">
           <form action="" method="post" class="">
            {% csrf_token %}
            <!-- 内容主界面 -->
            <div class="col-sm-4 col-md-4 container-fluid">
                {{ form.errors }}
                {{ form }}
                <div class="btn-group" aria-label="Basic outlined example" role="group">
                    <input type="submit" class="btn btn-success" value="登录">
                    <a href="{% url 'User:register' %}" class="btn btn-success" role="button">注册?</a>
                    <a href="{% url 'User:emailusername' %}" class="btn btn-success" role="button">忘记密码?</a>
                </div>
            </div>
            {#            <input type="submit" value="登录" class="btn btn-outline-success">#}
        </form>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %}
心音注册
{% endblock %}
<!-- 内容主界面 -->
{% block content %}
    <div class="container">
        <form action="" method="post">
            <div class="container">
                <div class="col-sm-4 col-md-4 container-fluid">
                   {% csrf_token %}
                {{ form.as_p}}
                </div>
                <div class="text-center">
                    <input type="submit" value="register" class="btn btn-outline-success">
                </div>
            </div>
        </form>
    </div>
    <div>
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}
    </div>
{% endblock %}

templates/submitEmailUsername.html
{% extends "base.html" %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="submit" class="btn btn-outline-success">
    </form>
{% endblock %}

templates/upload.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-sm-4 col-md-4 container-fluid">
            {{ form.as_p }}
        </div>
        <div class="text-center">
            <input type="submit" class="btn btn-success" value="上传">
        </div>

    </form>
</div>



{% endblock %}

templates/uploade_successful.html
{% extends "base.html" %}
{% block content %}
<div>

</div>
{% endblock %}